name: Test and Deploy pipeline

on:
  push:
    branches: [main]

env:
  GAR_HOSTNAME: europe-north1-docker.pkg.dev
  PROJECT_REPO: gridtests/gd-cicd
  IMG_NAME: demo-api
  REGION: europe-north1
  SERVICE: gd-cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: npm ci

      - name: Test
        run: npm test

  docker:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: GCP Auth
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Configure Docker
        run: gcloud auth configure-docker $GAR_HOSTNAME --quiet

      - name: Set Image Name
        run: echo "IMG_FULL_NAME=$GAR_HOSTNAME/$PROJECT_REPO/$IMG_NAME:${{ github.sha }}" >> $GITHUB_ENV
      
      - name: Build Docker
        run: docker build -t $IMG_FULL_NAME .

      - name: Scan Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMG_FULL_NAME }}
          severity: "CRITICAL,HIGH"
      
      - name: Push Image
        run: docker push $IMG_FULL_NAME

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: GCP Auth
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Deploy to Cloud Run    
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v3'
        with:
          service: ${{ env.SERVICE }}
          image: ${{ env.IMG_FULL_NAME }}
          region: ${{ env.REGION }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          flags: "--allow-unauthenticated"

      - name: 'Ping endpoint'
        run: 'curl "${{ steps.deploy.outputs.url }}/greet/CI-CD"'
